#!/usr/bin/env python3
"""Generate the mandate lookup widget from the funding datasets.

Answers a different question from the cost calculator. The calculator asks
"what will this cost"; this asks "what is my plan actually obliged to do".
Both read the same gated data.

The safety-critical branch is self-funded. A widget that tells a family
"yes, your plan must cover ABA" when their employer self-funds sends them
into an appeal they cannot win, so that branch is checked first and its
answer overrides everything else the mandate would otherwise say.

Run: python3 tools/blog/build-mandate-lookup.py [outfile]
Exit 0 only if every assertion holds.
"""
import json, pathlib, sys, re, hashlib

OUT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else
                   'content/blog/widgets/mandate-lookup.js')
PATH_GATE = '/insurance-terminology'
ANCHOR = 'Common Insurance Terms to Know'
STATES = ['new-jersey', 'georgia', 'north-carolina']
errs = []

funding = {s: json.load(open(f'data/funding/{s}.json')) for s in STATES}


def f(d, a, b):
    return d[a][b]


model = {}
for s in STATES:
    d = funding[s]
    cap = f(d, 'mandate', 'annual_dollar_cap')
    m = {
        'name': d['state'],
        'effective': f(d, 'mandate', 'effective_date')['value'],
        'ageLimit': f(d, 'mandate', 'age_limit')['value'],
        'cap': cap['cap_usd'],
        'capStatus': cap['cap_status'],
        'visits': f(d, 'mandate', 'visit_or_hour_limits')['value'],
        'diagnosis': f(d, 'mandate', 'diagnosis_requirement')['value'],
        'order': f(d, 'mandate', 'prescription_or_referral_requirement')['value'],
        'selfFunded': f(d, 'self_funded_exemption', 'applies')['value'],
        'selfFundedTell': f(d, 'self_funded_exemption', 'how_a_family_can_tell')['value'],
        'medicaidAge': f(d, 'medicaid', 'age_limit')['value'],
        'medicaidPA': f(d, 'medicaid', 'prior_authorization')['value'],
        'appealInternal': f(d, 'appeals', 'internal_appeal_deadline')['value'],
        'appealBody': f(d, 'appeals', 'external_review_body')['value'],
        'appealDeadline': f(d, 'appeals', 'external_review_deadline')['value'],
        'appealExpedited': f(d, 'appeals', 'expedited_route')['value'],
    }
    # A FLAG prefix is an instruction to us, not copy for a parent. Strip it,
    # but keep the sentence after it: that text already says in plain words
    # what we could not source, and it renders inline under the field it
    # belongs to rather than in a footnote nobody reads.
    flagged = [k for k, v in m.items() if isinstance(v, str) and v.startswith('FLAG')]
    for k in flagged:
        m[k] = re.sub(r'^FLAG,\s*', '', m[k]).strip()
    m['flagged'] = flagged
    model[s] = m

    if not m['selfFunded'].lower().startswith('yes'):
        errs.append(f'{s}: self_funded_exemption.applies does not start with Yes; '
                    f'the widget assumes the exemption applies in all three states')
    if cap['cap_status'] not in ('rarely_applicable', 'stale_base_indexed',
                                 'applies_to_aba_only'):
        errs.append(f'{s}: unknown cap_status {cap["cap_status"]!r}')

if errs:
    for e in errs:
        print('ERROR', e)
    sys.exit(1)

payload = json.dumps({'states': model}, ensure_ascii=False, separators=(',', ':'))

js = '''/* Mandate lookup. GENERATED by tools/blog/build-mandate-lookup.py.
   Do not edit by hand: every claim is read out of data/funding/*.json and
   asserted at build time. Edit the data, rebuild. */
(function () {
  "use strict";
  if (location.pathname.replace(/\\/+$/, "") !== "%PATH%") return;
  var D = %PAYLOAD%;

  // Insert above the terms section. No Designer edit needed, and if the
  // heading is ever renamed the widget simply does not render rather than
  // landing somewhere senseless.
  var anchor = null;
  var heads = document.querySelectorAll("h2, h3");
  for (var i = 0; i < heads.length; i++) {
    if ((heads[i].textContent || "").trim().indexOf("%ANCHOR%") === 0) {
      anchor = heads[i]; break;
    }
  }
  if (!anchor) return;

  var root = document.createElement("div");
  root.id = "mm-mlw";
  anchor.parentNode.insertBefore(root, anchor);

  root.innerHTML = [
    '<div class="mm-mlw-box">',
    '  <div class="mm-mlw-h">What is your plan actually obliged to cover?</div>',
    '  <p class="mm-mlw-sub">Three questions. The answers come from the statute, the Medicaid manual and the insurance regulator in your state, each dated.</p>',
    '  <div class="mm-mlw-row">',
    '    <label>State<select id="mm-mlw-state"></select></label>',
    '    <label>Your plan<select id="mm-mlw-plan">',
    '      <option value="insured">Bought from an insurer</option>',
    '      <option value="selffunded">Self-funded by my employer</option>',
    '      <option value="unsure">I am not sure</option>',
    '      <option value="medicaid">Medicaid</option>',
    '    </select></label>',
    '    <label>Child\\'s age<input id="mm-mlw-age" type="number" min="0" max="30" step="1" value="6"></label>',
    '  </div>',
    '  <div id="mm-mlw-out" class="mm-mlw-out"></div>',
    '</div>'
  ].join("");

  var sel = root.querySelector("#mm-mlw-state");
  Object.keys(D.states).forEach(function (k) {
    var o = document.createElement("option");
    o.value = k; o.textContent = D.states[k].name; sel.appendChild(o);
  });

  function p(html) { return "<p>" + html + "</p>"; }
  function note(html) { return '<p class="mm-mlw-note">' + html + "</p>"; }

  function render() {
    var s = D.states[sel.value];
    var plan = root.querySelector("#mm-mlw-plan").value;
    var age = parseInt(root.querySelector("#mm-mlw-age").value, 10);
    var out = [];

    if (plan === "unsure") {
      out.push(p("<b>Find this out first. It changes every other answer.</b>"));
      out.push(p(s.selfFundedTell));
      out.push(note("Come back to this once you know. Until then nothing below is reliable for your family."));
      root.querySelector("#mm-mlw-out").innerHTML = out.join("");
      return;
    }

    if (plan === "selffunded") {
      out.push(p("<b>The " + s.name + " mandate does not reach your plan.</b>"));
      out.push(p(s.selfFunded));
      out.push(note("This is not the same as having no rights. Self-funded plans carry federal appeal rights, and many cover ABA without being compelled to. It does mean the state cap, the state deadline and the state regulator are not levers you hold."));
      root.querySelector("#mm-mlw-out").innerHTML = out.join("");
      return;
    }

    if (plan === "medicaid") {
      out.push(p("<b>Medicaid in " + s.name + ".</b>"));
      out.push(p("<b>Age.</b> " + s.medicaidAge));
      out.push(p("<b>Prior authorization.</b> " + s.medicaidPA));
      out.push(note("Medicaid appeals run through the Medicaid process, not the insurance regulator named below."));
      root.querySelector("#mm-mlw-out").innerHTML = out.join("");
      return;
    }

    // fully insured
    out.push(p("<b>The " + s.name + " mandate applies to your plan.</b> " + s.effective));
    out.push(p("<b>Age.</b> " + s.ageLimit));
    if (!isNaN(age) && age >= 21) {
      out.push(note("At " + age + ", read that age wording closely. Several of these limits are written as something a plan <i>may</i> apply rather than something it must, and the Medicaid position can differ from the insurance one."));
    }
    out.push(p("<b>Dollar cap.</b> $" + s.cap.toLocaleString("en-US") + " a year, with a catch. " + capCatch(s.capStatus)));
    out.push(p("<b>Visit limits.</b> " + s.visits));
    out.push(p("<b>Who has to diagnose it.</b> " + s.diagnosis));
    out.push(p("<b>Do you need an order first?</b> " + s.order));
    out.push(p("<b>If you are refused.</b> " + s.appealInternal));
    out.push(p("<b>Then external review.</b> " + s.appealBody));
    out.push(p("<b>How long you have.</b> " + s.appealDeadline));
    out.push(p("<b>If it is urgent.</b> " + s.appealExpedited));

    root.querySelector("#mm-mlw-out").innerHTML = out.join("");
  }

  function capCatch(status) {
    if (status === "rarely_applicable") {
      return "Your plan often cannot lawfully apply it. Ask the insurer to confirm in writing whether it is applying a dollar maximum to ABA, and why.";
    }
    if (status === "stale_base_indexed") {
      return "That figure is a base the statute has indexed for years, not the live ceiling, and we could not find the current amount published anywhere citable. Ask your insurer for it in writing.";
    }
    return "It applies to applied behavior analysis specifically, and it is a ceiling a plan may apply rather than a budget you are given.";
  }

  root.addEventListener("input", render);
  root.addEventListener("change", render);
  render();
})();
'''.replace('%PATH%', PATH_GATE).replace('%ANCHOR%', ANCHOR).replace('%PAYLOAD%', payload)

# ---------------------------------------------------------------- gates
g = []
if 'FLAG,' in js:
    g.append('a raw FLAG, prefix leaked into widget copy')
if re.search(r'[—–]', js):
    g.append('em or en dash in widget copy')
if re.search(r'\bRBT\b', js):
    g.append('RBT acronym in widget copy')
if PATH_GATE not in js or 'location.pathname' not in js:
    g.append('widget is not path-gated')
if ANCHOR not in js:
    g.append('anchor heading missing, widget would have nowhere to mount')
# the self-funded branch must come before any "the mandate applies" line
if js.index('does not reach your plan') > js.index('mandate applies to your plan'):
    g.append('the self-funded branch must be evaluated before the mandate-applies branch')
for m in re.finditer(r'\$\d[\d,]{2,}', js):
    if not any(m.group(0) == f'${x["cap"]:,}' for x in model.values()):
        g.append(f'unexplained currency literal: {m.group(0)}')
if g:
    for e in g:
        print('GATE', e)
    sys.exit(1)

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(js, encoding='utf-8')
print(f'{len(js)} chars  md5={hashlib.md5(js.encode()).hexdigest()}')
print(f'states: {", ".join(model)}')
for k, m in model.items():
    print(f'{k}: flagged fields rendered inline -> {m["flagged"] or "none"}')
